### ISSUE TITLE
Stuck on Requesting Data

### ISSUE THREAD

**Issue by GMDarkRPModule** [Weol/WUMA#11]
Hey,

It is constantly stuck on the green loading bar saying "requesting data" forever no matter what, even after restart any everything. Why is this happening?

**Comment by GMDarkRPModule** [comment]
Okay so I worked out that I needed to be in the super admin group for it to work. 

However now, I derestricted a tool from a group and they still get the 'admins only' message. Why is this?

**Comment by Weol** [comment]
Does the message say exactly "admin only"? Because that is not a WUMA message, maybe another addon is restricting it, like FPP or something?

**Comment by GMDarkRPModule** [comment]
I totally forgot about FPP, disabling it fixed everything. Thanks.
