### ISSUE TITLE
Advanced Duplicator 2 Error loop

### ISSUE THREAD

**Issue by ayyjacks** [Weol/WUMA#12]
At random I will see this error in my logs. It continues until the server crashes or the map changes, which can generate massive log files. I do not know exactly which dupes trigger it.

L 07/27/2018 - 16:13:13: Lua Error: 
[Advanced Duplicator] addons/sboxgit_wuma/lua/wuma/duplicator.lua:34: Tried to use a NULL entity!
  1. GetClass - [C]:-1
   2. fn - addons/sboxgit_wuma/lua/wuma/duplicator.lua:34
    3. Run - addons/git_ulib/lua/ulib/shared/hook.lua:109
     4. FinishPasting - lua/autorun/server/advdupe.lua:2412
      5. fn - lua/autorun/server/advdupe.lua:1761
       6. unknown - addons/git_ulib/lua/ulib/shared/hook.lua:109

**Comment by Weol** [comment]
Does it affect anything else or does it simply spam?

**Comment by ayyjacks** [comment]
I don't think it affects anything other than creating a 1GB log file and probably failing whichever dupe is being spawned

**Comment by Weol** [comment]
Fixed by https://github.com/Weol/wuma/commit/9dbe2b5a037f40e09a7e2e74b9475ece8754bfc7

I added a IsValid check so that WUMA will ignore all NULL entities, this should stop these errors.
