### ISSUE TITLE
Can you whitelist certain props instead of restrict ?

### ISSUE THREAD

**Issue by Synkstar** [Weol/WUMA#14]
This is for a darkrp I want it so users can only spawn certain props. But I also need admins to be able to  spawn all props. I can do white listing in fpp but it does not allow you to do it for certain ranks just everyone including the owner.

**Comment by Weol** [comment]
I think the only way to do that is by using inheritance. If you create a new usergroup and restrict props from them, and then make your user's usergroup inherit from the new usergroup. Then you can add anti-restrictions to the user's usergroup to counteract the inherited prop restriction, effectivly whitelisting themm.

**Comment by Synkstar** [comment]
It would be cool if you could add a check box that makes a ranks restrictions under a certain category a white list

**Comment by Weol** [comment]
Yeah, I'll definitely do that. You can use this method until that update arrives, don't know when I will get the time. 

I just pushed an update, so make sure you update or the method wont work.
