### ISSUE TITLE
Can you make it so you cant spawn restricted items using dupe and advanced dupe 2 ?

### ISSUE THREAD

**Issue by Synkstar** [Weol/WUMA#15]
Right now people can bypass restrictions using duplicator if you don't have it restricted. I want it so I can allow dupe without people bypassing restrictions. Thank you for your time.

**Comment by Weol** [comment]
Hmm, this should already be a feature. Can you check if you can bypass ALL restrictions, or just restrictions on certain things?

**Comment by Synkstar** [comment]
I tried expression 2. If I get the time I will try other things.

**Comment by Synkstar** [comment]
It doesnt allow restricted props to be duped

**Comment by Synkstar** [comment]
But it does allow sents like balls for example

**Comment by Weol** [comment]
That is odd, I'll have closer look. Can you link me a list of any addons you are using? It will help me recreate your issue.

**Comment by Synkstar** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1401467255

**Comment by Synkstar** [comment]
I mean it doesnt allow restricted props to be duped but it does allow  restricted sents and restricted wire things for example

**Comment by Weol** [comment]
What kind of restriction are you using to restrict these? Because entities that are spawned with tools are often not listed in the "Entities" list. Wire expression2 for example, the tool spawns an entity called "gmod_wire_expression2", that must be restricted in order to prevent it from beeing spawned by the duplicator.

I'll see if I can do something to make those entities easier to find.

**Comment by Synkstar** [comment]
Oh that makes sense I was using the tool restriction for expression and the sent restrictions for the ball

**Comment by Weol** [comment]
I just pushed an update (https://github.com/Weol/wuma/commit/10ffb694a77a3934b4a59c43dce69571361932b3) that adds some entities that were missing to the entity restriction list. I can't promise that all items for all addons will be there, but hopefully they will. I tested it with wiremod and darkrp atleast.

If you have trouble finding which entity corresponds to which tool, you can set the "Log level" setting to "Debug", then every restriction check will be printed to the server console, and you can see the entity names that are checked.
