### ISSUE TITLE
Limit Sorting

### ISSUE THREAD

**Issue by ghost** [Weol/WUMA#17]
This is just a little request. On the Limit window its hard to make the limits for each weapon.. could you add like in the restriction panel a sorting feature for weapons and so on cuz its kinda mixed all of the things.

and another feature could be that u cannot spawn the weapon in the loadout if limit is 0.. 
i mean on limit 0 you can spawn the weapon as a loadout  (i mean it appears n the invetory)  but if you spawn the swep with the toolgun limit 0 works and you cannot spawn it.

thanks alot

**Comment by Weol** [comment]
You can search for weapons in the searchbox above the list, most weapons contains "weapon" in them, you can also go into the restrictions tab and check which weapons are there. I would like to have some sort of sorting feature, but I don't have alot of time to work on this atm. 

As to the other feature; it is not something I can do anything with, that is just how Garry's Mod handles weapon spawning. If something has a limit of 0 then you might as well restrict it, if you restrict it in "Weapons" and in "Pickup" then nobody can spawn or pick them up.
