### ISSUE TITLE
Addon wont save after map change

### ISSUE THREAD

**Issue by haleylovesroses** [Weol/WUMA#2]
This addon wont write the text files for some reason on the server. It is not saving changes between map changes and reboots.

**Comment by haleylovesroses** [comment]
These are the ONLY addons that i have installed as a test and it still wont create or write the config files called restrictions.txt, log.txt, and loadouts.txt.

Build Mode (chat command) - View on Workshop
CustomCommands - View on Workshop
ULib - View on Workshop
ULX - View on Workshop
ULX Cleanup Kit - View on Workshop
ULX Server Mail - View on Workshop
WUMA - View on Workshop

**Comment by haleylovesroses** [comment]
ok i went through your coding and corrected a couple things. Changing the directories to the ulx directory corrected the problem. Here is the corrected code. 

16 --Paths
17 WUMA.DataDirectory = "ulx/"
18 WUMA.SharedDirectroy = "wuma/shared/"
19 WUMA.ClientDirectory = "wuma/client/"
20 WUMA.ObjectsDirectory = "wuma/objects/"
21 WUMA.UserDataDirectory = "wuma_users/"
22 WUMA.HomeDirectory = "wuma/"

Changing the directories allowed xgui to write to those directories and now the config files are being written and loaded properly.

**Comment by Weol** [comment]
Restore the addon to its orginal state and change _data_save_delay_ option in Advanced Server Settings to 0. That will make the changes to be saved to file immediately, check if the changes get saved between map changes and reboots.

**Comment by Weol** [comment]
This was fixed by 4dcd2bff4416bc27b4d33a9f90b3bf6da2fcf78c

Thank you for bringing this to my attention.
