### ISSUE TITLE
Data save issue

### ISSUE THREAD

**Issue by St11l** [Weol/WUMA#24]
Hello.
If set limits and rejoin, then open list of usergroup limits and click on another usergroup- the list becomes empty. Lua error appears if press the RMB

https://i.imgur.com/uJ2LocU.gifv

**Comment by Weol** [comment]
Hi, can you open your console and copy the error that appears when you do this? Also, when you rejoin after this happens, does the limit appear again?

**Comment by St11l** [comment]
[ERROR] addons/ulx_wuma/lua/wuma/client/vgui/vgui_limits.lua:152: attempt to index local 'item' (a nil value)
  1. RightClickFunction - addons/ulx_wuma/lua/wuma/client/vgui/vgui_limits.lua:152
   2. OnRowRightClick - addons/ulx_wuma/lua/wuma/client/vgui/vgui_dataview.lua:104
    3. unknown - lua/vgui/dlistview_line.lua:74

**Comment by St11l** [comment]
After rejoin it repeats. All limits works, but in menu appears error

**Comment by Weol** [comment]
Okay, then this is a client-side issue. I will fix this, thank you for letting me know

**Comment by Weol** [comment]
I have pushed a fix for this: fd1e291e90c6f8fe5b4f6d77b152cfd4e3287883

**Comment by Weol** [comment]
Would be nice if you could confirm that this is no longer an issue

**Comment by St11l** [comment]
Thank u, error solved. But one more problem remained
> If set limits and rejoin, then open list of usergroup limits and click on another usergroup - the list becomes empty

**Comment by Weol** [comment]
Do the limits appear again if you click back to the previously selected usergroup?

**Comment by St11l** [comment]
No. Limits work fine, but this error only in menu
