### ISSUE TITLE
Problem with data

### ISSUE THREAD

**Issue by tomekb530** [Weol/WUMA#27]
Hi, I have problem with requesting data in wuma, heres gif that shows the problem http://screen.tomekb530.me/tomek/RectangularBurro2106

**Comment by Weol** [comment]
And no error shows up console?

Other people have had the same problem, I'll see what can be done.

**Comment by tomekb530** [comment]
No errors

**Comment by Weol** [comment]
And it only happens in the limit tab?

**Comment by tomekb530** [comment]
All tabs

**Comment by Weol** [comment]
I pushed an update (1e21da03ae2759472b94547d13193af258a9881a), I think this will fix your issues. I have pushed the update to the steam workshop as well.

I would appreciate it if you would test it, so we can confirm that it is resolved.

**Comment by tomekb530** [comment]
Working like a charm!
