### ISSUE TITLE
Instead of storing redundant data in SQL for lookup, use ULib.ucl

### ISSUE THREAD

**Issue by storm37000** [Weol/WUMA#29]
Instead of storing redundant data in SQL for lookup you should use ULib.ucl.  This table contains all data that is needed, it is indexed by steamid and contains the group and username. For EX (from PrintTable(ULib.ucl) and anonymised);
```
STEAM_0:0:00000000:
                                allow:
                                deny:
                                group   =       admin
                                name    =       myusername

**Comment by Weol** [comment]
This would work fine, but would make WUMA dependent on ULib.
