### ISSUE TITLE
Usergroups not showing in list

### ISSUE THREAD

**Issue by haleylovesroses** [Weol/WUMA#3]
Now i'm not getting usergroups to show in the list. Its not restricting anymore.

**Comment by haleylovesroses** [comment]
I ended up going back to URM until this is more stable. YES it may be slower in the database, BUT it's performance is stable and worked out of the box with no glitches.

**Comment by Weol** [comment]
I cannot recreate this, are you 100% certain you are using the latest version? Were there no errors at all? Any errors that had _wuma_ in it?

**Comment by haleylovesroses** [comment]
i am 100% sure and there were no errors, just the usergroups tab was blank. I have ALOT of usergroups maybe it was too many to handle? IDK i'm perfectly satisfied with URM at this point: your old script: it works flawlessly.

**Comment by Weol** [comment]
Okay, how many (ish)? 10+? 40+? 100+?

**Comment by haleylovesroses** [comment]
I'd say around 15ish
