### ISSUE TITLE
SENT limit issue when wiremod things are spawned with any duplicator

### ISSUE THREAD

**Issue by storm37000** [Weol/WUMA#32]
having an issue where wire things spawned in with any duplicator(adv1,adv2,and vanilla) count against your sent limit, and still count even when removed.  They shouldn't even count against SENT limits, only their particular wire limits.

**Comment by Weol** [comment]
I will look into this. Do you know if this happens for all wire things, like gates, sensors, thrusters, wheels, and so on, or if it only happens for some wire things?

**Comment by storm37000** [comment]
I think it was just thrusters and gates.  It wasn't me that found this but people that play on my server.

**Comment by storm37000** [comment]
i haven't heard reports of this issue anymore, it was likely fixed. i will close until i hear reports of it again if it happens again.
