### ISSUE TITLE
Restrict Type Issue

### ISSUE THREAD

**Issue by Terra121** [Weol/WUMA#34]
I am trying to restrict type prop to the usergroup user. It says adding data but it has said that for a couple hours. I am guessing that is not supposed to happen. I was tabbed out for a little which idk if it affects it and I closed the menu for sometime. The list of addons my server has rn is in this content pack https://steamcommunity.com/sharedfiles/filedetails/?id=1971786852

**Comment by Weol** [comment]
Is the restriction still added? Can you spawn props when it says adding data? If you re-join your server is the restriction in place?

Also, I see you are running URS alongside WUMA, I recommend not doing this as they are likely to cause conflicts.

**Comment by Weol** [comment]
This has been fixed by @Wgis #35
