### ISSUE TITLE
WUMA not loading saved restrictions.

### ISSUE THREAD

**Issue by Weldeasy** [Weol/WUMA#36]
When I restart the server, no restrictions are applied.

I've checked and the files and permissions are ok (I think).

/../garrysmod/data/wuma/restrictions.txt

**Comment by Weldeasy** [comment]
In the logs seems to be loading OK:

//  end.lua                  //
// Load Complete!            //
///////////////////////////////
Wiremod Version 'Workshop' loaded
[WUMA] Weol's User Management Addon version 1.3.0
[WUMA] Loading shared files
[WUMA] Loading client files
 +---------------------------------+
 |          E2 EXTENSIONS          |
 +----------------+----------------+
 |    ENABLED     |    DISABLED    |

**Comment by Weol** [comment]
So when you add a restriction it works, but when you restart the server the restriction is gone? Have you tried deleting the file and letting the server generate it anew?

**Comment by Weldeasy** [comment]
Done and working. Thanks!
