### ISSUE TITLE
loadout restriction bug 

### ISSUE THREAD

**Issue by horvik-pyysalo** [Weol/WUMA#39]
Hello, I do have a little problem on my server, I have restricted some weapons to admin only, but users can still give themself theses weapons with the loadout :/ can you fix it or if it's an option to change, can you explain me ?

Thanks in advance !

**Comment by Weol** [comment]
Have you restricted both "pickup" and "swep" types for all the weapons? Because users should not be able to add weapons that have been "pickup" restricted.
