### ISSUE TITLE
WUMA incompatible with SwiftAC

### ISSUE THREAD

**Issue by Megamezzomixer** [Weol/WUMA#40]
Hey there,
We are using WUMA about 2 months on the server now and it works great.
But I have encountered errors when installing SwiftAC from gmodstore.
Our console error output:

`[WUMA] lua/includes/modules/hook.lua:120: attempt to index local 'gm' (a number value) 1. Call - lua/includes/modules/hook.lua:120 2. OnLoseFocus - lua/wuma/client/vgui/vgui_textbox.lua:79 3. SetDefault - lua/wuma/client/vgui/vgui_textbox.lua:13 4. Init - lua/wuma/client/vgui/vgui_restrictions.lua:30 5. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37 6. unknown - lua/wuma/client/gui.lua:65`

And my client console output:
```
[ERROR] lua/includes/modules/hook.lua:120: attempt to index local 'gm' (a number value)
 1. Call - lua/includes/modules/hook.lua:120
  2. fn - addons/ulib-master/lua/ulib/cl_init.lua:58
   3. func - addons/ulib-master/lua/ulib/client/cl_util.lua:22
    4. unknown - lua/includes/extensions/net.lua:32
```

I've both contacted you and the dev of SwiftAC.

**Comment by Weol** [comment]
Is this a paid addon? I need the source code of the addon in order to find exactly what is causing it.

**Comment by Megamezzomixer** [comment]
Yes, it is. Sadly I can't provide the source code, as it would violate their ToS and I can get in trouble for it.

**Comment by Weol** [comment]
Hmm, that makes it hard. I've tried a fix that might work. Try to download and use this version of WUMA: https://github.com/Weol/wuma/tree/test

Its a different version with a very minorr change that might fix this exact issue.

**Comment by Megamezzomixer** [comment]
Will do. I also added you on steam (same name) to solve the source code issue.

**Comment by Megamezzomixer** [comment]
EDIT: The solution has partially worked. Now I can see the WUMA interface in ULX again, but there are still errors.

`Lua Error: [ERROR] lua/includes/modules/hook.lua:120: attempt to index local 'gm' (a number value) 1. Call - lua/includes/modules/hook.lua:120 2. fn - addons/ulib-master/lua/ulib/cl_init.lua:58 3. func - addons/ulib-master/lua/ulib/client/cl_util.lua:22 4. unknown - lua/includes/extensions/net.lua:32`

`Lua Error: [ERROR] lua/includes/modules/hook.lua:120: attempt to index local 'gm' (a number value) 1. Call - lua/includes/modules/hook.lua:120 2. execute - addons/ulib-master/lua/ulib/shared/commands.lua:1329 3. unknown - addons/ulib-master/lua/ulib/shared/commands.lua:1359 4. unknown - lua/includes/modules/concommand.lua:54`
Followed by
`Lua Error: ULib queue error: lua/includes/modules/hook.lua:120: attempt to index local 'gm' (a number value) `

**Comment by Megamezzomixer** [comment]
Also by typing xgui in console (That's my bind to open ULX) I get the error above. !menu works, but WUMA is endlessly "Decompressing data".
EDIT: We have a stock ULib.

**Comment by Weol** [comment]
Allright, I think I know what the problem is. For context: many addons use "\_" in order to represent an empty (nil) value. I think that this anti-cheat addon has globally defined "\_" as 1. As you can see from the errors, ULib is also broken because of this.

**Comment by Weol** [comment]
I would contact the author of SwiftAC to resolve it

**Comment by Megamezzomixer** [comment]
That would be good, as I cannot share the source code without risking trouble.

**Comment by Weol** [comment]
Yea, just link him to this issue I guess.

**Comment by Weol** [comment]
Issue caused by different addon.
