### ISSUE TITLE
Unable to spawn anything

### ISSUE THREAD

**Issue by SirChryse** [Weol/WUMA#42]
I'm the owner of a server and I set the limit amount for props to infinity for my usergroup, however it keeps giving an error saying something about exceeding the prop limit.

**Comment by Weol** [comment]
When you say error, do you mean the "You have hit the prop limit" notification, or do you mean actual lua errors in the client or server console? 

Also check all this:
* Check that you dont have a a user specific limit that overrides your usergroup's limit. 
* Check that you set the "props" limit and not "prop" limit. 
* Check that the "Exclude limits from gamemode limits" checkbox in the settings tab is checked.
