### ISSUE TITLE
Prop restrictions dont inherit 

### ISSUE THREAD

**Issue by Synkstar** [Weol/WUMA#45]
Everything else inherits restrictions besides props for some reason

**Comment by Weol** [comment]
I will investigate

**Comment by Weol** [comment]
Hmm, prop restrictions inherits on my test server. Do the prop restrictions work if you are the actual usergroup for whom its restricted?

Also make sure you dont have any anti-restrictions on yourself that override the inherited prop restrictions?

**Comment by Synkstar** [comment]
Yes they do also sorry I didnt notice this ... But realized that I have an anti restriction set on one group and I guess I forgot then lol. So no issue sorry
