### ISSUE TITLE
Sents with custom limits(like wiremod) counting as sents when duping alongside normal sents

### ISSUE THREAD

**Issue by storm37000** [Weol/WUMA#47]
https://youtu.be/zo96YkKd1Jk
vanilla sent limit set at 2 using vanilla convar, not messing with sent limit in WUMA at all.

**Comment by Weol** [comment]
Let me get this straight, you have set some WUMA limits on some sents, which should not count towards the vanilla convar sent limit. But when you duplicate the sents they count towards the vanilla convar sents limit after all?

**Comment by Weol** [comment]
I've found the issue that causes the problem your video shows. I'll push a fix out soon.

**Comment by Weol** [comment]
Fixed by 9e3f65d9e71b6e44df8896959c2b448e4625a2a3
