### ISSUE TITLE
Wuma Menu is Not Working

### ISSUE THREAD

**Issue by Azboy4God** [Weol/WUMA#55]
[wuma-master] addons/wuma-master/lua/wuma/client/gui.lua:113: attempt to index field 'Base' (a nil value)
  1. Toggle - addons/wuma-master/lua/wuma/client/gui.lua:113
   2. unknown - LuaCmd:1

This error is the result of typing "wuma_menu" in the console. Needless to say, the menu does not appear. Additionally, the wuma tab on the ulx menu is blank.

List of addons:
3D Stream Radio - View on Workshop
[ Stormfox ] Resources - View on Workshop
[ArcCW] Arctic's Customizable Weapons (Base Only) - View on Workshop
[ArcCW] Counter-Strike + - View on Workshop
[ArcCW] M9K/CSS Extras Pack - View on Workshop
[E2] Vgui Core - View on Workshop
[LFS] - Planes - View on Workshop
[LFS] BF3 Fighter jets - View on Workshop
[LFS] BF3-4 Attack jets - View on Workshop
[LFS] BF4 Attack helicopters - View on Workshop
[LFS] UH-60 Black Hawk (TSK/Polis) - View on Workshop
[Offical] Autopromote (APromote) for ULX - View on Workshop
[Official] Precision Tool - View on Workshop
[simfphys] armed vehicles - View on Workshop
[simfphys] GTA San Andreas Cars - View on Workshop
[simfphys] Hydraulics System for Lowriders - View on Workshop
[simfphys] LUA Vehicles - Base - View on Workshop
[Simfphys] M42A1 Duster - View on Workshop
[Simfphys] StuG III Ausf. G - View on Workshop
[SWEP] King Crimson Time Skip - View on Workshop
[TFA] [AT] M14 & SW M10 - View on Workshop
[TFA] RPG-7 - View on Workshop
[TFA][AT] AK-12 + GP-25 - View on Workshop
[TFA][AT] AR-15 - View on Workshop
[TFA][AT] Benelli Nova Tactical - View on Workshop
[TFA][AT] Beretta M9 - View on Workshop
[TFA][AT] Blitz Sight Pack - View on Workshop
[TFA][AT] Colt King Cobra - View on Workshop
[TFA][AT] CZ 805 BREN - View on Workshop
[TFA][AT] FAMAS F1 - View on Workshop
[TFA][AT] Glock P80 - View on Workshop
[TFA][AT] GOL Magnum - View on Workshop
[TFA][AT] H&K MP5K - View on Workshop
[TFA][AT] H&K MP7 - View on Workshop
[TFA][AT] H&K UMP .45 - View on Workshop
[TFA][AT] H&K USP Match - View on Workshop
[TFA][AT] IMI Desert Eagle .50 - View on Workshop
[TFA][AT] INS2 Shared Parts - View on Workshop
[TFA][AT] Kar 98k - View on Workshop
[TFA][AT] Keep your attachments after death - View on Workshop
[TFA][AT] Kriss Vector - View on Workshop
[TFA][AT] KSG - View on Workshop
[TFA][AT] M1014 - View on Workshop
[TFA][AT] M249 Para - View on Workshop
[TFA][AT] Mateba Unica 6 - View on Workshop
[TFA][AT] MK18 - View on Workshop
[TFA][AT] Mossberg M500 - View on Workshop
[TFA][AT] P90 - View on Workshop
[TFA][AT] Remington ACR - View on Workshop
[TFA][AT] SA80 (L85A2) - View on Workshop
[TFA][AT] Scopes Pack - View on Workshop
[TFA][AT] Scorpion Evo 3 - View on Workshop
[TFA][AT] Sights Pack - View on Workshop
[TFA][AT] SKS - View on Workshop
[TFA][AT] Smith & Wesson 659 - View on Workshop
[TFA][AT] SPAS-12 - View on Workshop
[TFA][AT] Spectre M4 - View on Workshop
[TFA][AT] Sterling - View on Workshop
[TFA][AT]Battle-Worn AKM - View on Workshop
[TFA][AT]Fort-500 - View on Workshop
[TFA][AT]INS2 GiTS Sights Extension - View on Workshop
[TFA][AT]Insurgency Austro-German Pack (AUG, G3A3, Glock 17 & MP5A4) - View on Workshop
[TFA][AT]Insurgency Communist Pack #2 (AS VAL, MN91, PPSH-41 & SVD) - View on Workshop
[TFA][AT]Insurgency Mixed Weapons Pack (D-25S, G36C, PM Makarov & SCAR-L) - View on Workshop
[TFA][AT]M1A SOCOM 16 - View on Workshop
[TFA][AT]MWR Shared Pack - View on Workshop
[TFA][AT]MWR Snipers Pt.1 - View on Workshop
[TFA]Insurgency Explosives Pack #1 (F1 & M67) - View on Workshop
[ULX] Sui Scoreboard w/ Utime (Sandbox) Redesign - View on Workshop
ACF Missiles Support Pack - View on Workshop
ACF Sound Extension Project - View on Workshop
ACF Unofficial Extras - View on Workshop
ACF Warthunder Sounds - Guns - View on Workshop
Advanced Axis - View on Workshop
Advanced Ball Socket Tool (Adv. Ballsocket) - View on Workshop
Advanced Duplicator 2 - View on Workshop
Aimbot Gun - View on Workshop
Alydus's Fortification Builder Tablet - View on Workshop
Anti-Noclip Field - View on Workshop
Arctic's Vehicle Extension - View on Workshop
Axis and Ballsocket Centre - View on Workshop
Backhopping Unfix - View on Workshop
Buoyancy Tool - View on Workshop
Centre Tools REUP - View on Workshop
Chat Tick - View on Workshop
Collision Resizer (ENHANCED) - View on Workshop
ColorMater Tool - View on Workshop
Connect/Disconnect Messages - View on Workshop
Constraint Remover Tool - View on Workshop
CS:GO Knives SWEPs - View on Workshop
Custom ULX Commands - View on Workshop
Disguise SWEP - View on Workshop
Door STool - View on Workshop
Doors - View on Workshop
DPP/2 - Next Gen Prop Protection - View on Workshop
Drones Rewrite - View on Workshop
Dynamic Height + Crouch Fix - View on Workshop
E2 Viewer - View on Workshop
Easy Advanced Ballsocket - View on Workshop
Easy Ballsocket - View on Workshop
Elastic Suspension Tool - View on Workshop
Extended Properties - View on Workshop
Extended Spawnmenu - View on Workshop
Fading door tool - View on Workshop
Fading Door Tool - Fixed - View on Workshop
Falco's Prop Protection (FPP) - View on Workshop
Fightspace 3b - View on Workshop
Fire Extinguisher - View on Workshop
Food and Household items - View on Workshop
Forcefields V2 - View on Workshop
Fps Booster - View on Workshop
Freespace 13 - View on Workshop
Friendly Gnome - View on Workshop
GBombs 5 - Base - View on Workshop
GBombs 5 - Chemicals - View on Workshop
GBombs 5 - Materials - View on Workshop
Gesture Menu & Commands - View on Workshop
gm_7eleven - View on Workshop
gm_atomic - View on Workshop
gm_bigcity - View on Workshop
gm_bigcity_improved - View on Workshop
gm_bluehills_test3 - View on Workshop
gm_boreas - View on Workshop
gm_buttes - View on Workshop
gm_buttes 2 - View on Workshop
gm_fork - View on Workshop
GM_Functional_Flatgrass - View on Workshop
gm_genesis - View on Workshop
Gm_Highway14800 - View on Workshop
GM_MARSH - View on Workshop
GM_Vagiland - View on Workshop
gm_vyten - View on Workshop
gm_warmap_v5 - View on Workshop
GMod Pee Mod 2.0 - View on Workshop
GmodAdminSuite - View on Workshop
Hit Numbers - View on Workshop
HomeTown 1999 - View on Workshop
Improved Stacker - View on Workshop
JMod - View on Workshop
JMod Assets (materials 1/2) - View on Workshop
JMod Assets (materials 2/2) - View on Workshop
JMod Assets (sounds 1/1) - View on Workshop
Keypad Tool and Cracker with Wire Support - View on Workshop
LED screens - View on Workshop
M1A0 Cat Gun - View on Workshop
Make Spherical - View on Workshop
MBilliards - Revamp [Beta, Discontinued for now] - View on Workshop
MD4A V0.097 - View on Workshop
Media Player - View on Workshop
Merydian's LFS stuff - View on Workshop
Mobile Spawnpoint 2 - View on Workshop
More Materials! - View on Workshop
Multi-Parent / Unparent Tool - View on Workshop
Multiple Advanced RT Cameras - View on Workshop
New Door sTool - View on Workshop
Nexus Core (E2 Functions) - View on Workshop
No Collide - Multi - View on Workshop
No Collide Everything - View on Workshop
Outfitter: Multiplayer player models - View on Workshop
PAC3 - View on Workshop
Parkour Skill 1.7.5 - View on Workshop
Patrol Routes STool - View on Workshop
PermaProps - View on Workshop
Physical Clip Tool [Reupload] - View on Workshop
PlayX - View on Workshop
Precision Alignment - View on Workshop
Prop Shadow Remover - View on Workshop
Resizer - View on Workshop
RT Camera - View on Workshop
Safe Space - View on Workshop
SCP 106 from SCP - Containment Breach - View on Workshop
SCP Insanity - View on Workshop
Screengrab - View on Workshop
Seat Weaponiser II - View on Workshop
SGM Shared Textures - View on Workshop
Simple ThirdPerson - Sliders & Fixes! - View on Workshop
SligWolf's Bus and BendyBus - View on Workshop
Smart Weld - View on Workshop
SmartSnap - View on Workshop
SprayMon - View on Workshop
SProps Workshop Edition - View on Workshop
Stacker STool - View on Workshop
Stealthy Door Opening - View on Workshop
StormFox - Environment mod - View on Workshop
Sub Material Tool - View on Workshop
Tactical Leaning - View on Workshop
Tank Texture Pack - View on Workshop
Tank Track Tool - View on Workshop
TARDIS - View on Workshop
TARDIS Rewrite - View on Workshop
TDMCars - Base Pack - View on Workshop
TDMCars - European Trucks Pack - View on Workshop
TDMCars - Trailer Pack - View on Workshop
TFA Base [ Reduxed ] - View on Workshop
TFA CSO2 Assault - View on Workshop
TFA CSO2 Heavy Weapons - View on Workshop
TFA CSO2 Small Arms - View on Workshop
TFA][AT]Insurgency Israeli Palestinian Conflict Pack (AKM, IMI Galil, IMI UZI & PKP) - View on Workshop
Thanos's Infinity Gauntlet SWEP and Model - View on Workshop
The Only MeatBall Man - View on Workshop
The Prone Mod - View on Workshop
The Sit Anywhere Script! - View on Workshop
The Ultimate Admin Gun Fixed - View on Workshop
ULib by Team Ulysses
ULX by Team Ulysses
ULX Buildmode - View on Workshop
ULX Cleanup Kit (Reuploaded) - View on Workshop
ULX FPP Cleanup Commands - View on Workshop
Unbreakable Tool - View on Workshop
UnoLimited - View on Workshop
UTime by Megiddo (Team Ulysses)
Vagiland V2 - View on Workshop
Vagiland V2 Night - View on Workshop
vFire - Dynamic Fire for Garry's Mod - View on Workshop
Visual Clip Tool ( Could be broken! ) - View on Workshop
WAC Aircraft - View on Workshop
WAC Community 1 - View on Workshop
WAC Community 2 - View on Workshop
WAC Community 3 - View on Workshop
WAC Community 4 - View on Workshop
WAC Community 6 - View on Workshop
Weegee Nextbot - View on Workshop
Weight STool - View on Workshop
White Texture Pack [dev halted] - View on Workshop
Wiremod - View on Workshop
Wowozela - View on Workshop

**Comment by Weol** [comment]
Are these in a workshop collection somewhere so I can test it myself?

**Comment by Azboy4God** [comment]
Here is the collection:
https://steamcommunity.com/sharedfiles/filedetails/?id=2191603099

**Comment by Weol** [comment]
Fixed by 4d0c2f08dfd55a96a005fab27aab7584666cbdcc

The workshop collection was very helpful, thank you for opening the issue.

**Comment by Weol** [comment]
I've put the update on the workshop as well.

**Comment by Azboy4God** [comment]
Thank you so much! 👍

**Comment by Azboy4God** [comment]
@Weol I had actually figured out that the reason the addon wasn't working was because the master folder had capital letters. As soon as I replaced "WEOL" with "weol", I was able to start using the addon again.
