### ISSUE TITLE
When I start my server I receive this error.

### ISSUE THREAD

**Issue by timothybvf** [Weol/WUMA#57]
[WUMA - Restrictions, limits, and loadouts] lua/wuma/datahandler.lua:343: Tried to use a NULL entity!
1. SteamID - [C]:-1
2. GetUserFolder - lua/wuma/datahandler.lua:343
3. GetUserFile - lua/wuma/datahandler.lua:348
4. HasPersonalLoadout - lua/wuma/loadouts.lua:65
5. AssignUserLoadout - lua/wuma/users.lua:108
6. AssignLoadout - lua/wuma/users.lua:94
7. fn - lua/wuma/users.lua:263
8. Call - addons/ulib/lua/ulib/shared/hook.lua:109
9. GiveLoadout - lua/wuma/loadouts.lua:491
10. unknown - lua/wuma/loadouts.lua:501
Timer Failed! [Simple][@lua/wuma/loadouts.lua (line 500)]

https://steamcommunity.com/sharedfiles/filedetails/?id=2196565007 heres the addon list.

**Comment by Weol** [comment]
Hmm, I can't replicate the error on my test server using the addon list. Do you still get your loadout even if this error occurs?

**Comment by Weol** [comment]
I've pushed an update (957a71fb429759ca40269fa3ad5fc9f2926c77ff) to the steam workshop that I hope will fix this issue. 

Please test this and reply whether or not it has been fixed.

**Comment by timothybvf** [comment]
Yeah since the last update I haven't seen any errors, thanks Weol!
