### ISSUE TITLE
Fading Door Limit

### ISSUE THREAD

**Issue by Zytrol** [Weol/WUMA#63]
It might be me, but within limits there is an option for limits for fading doors when the mod is enabled on my server called "fading_door", however this seems to not do anything. Not sure if this is a glitch or not, but it would be nice to have a fading door limit that works with fading doors (or if you know another way to limit fading doors that would also be great). I am using this fading door mod: https://steamcommunity.com/linkfilter/?url=http://www.garrysmod.org/downloads/?a=view&id=110306

Unsure how to mark this as a suggestions or whatever but I hope this works, thank you for your time and thank you for this amazing mod.

**Comment by Weol** [comment]
I took a look at the source code and it appears that the fading door tool does not support any limits. WUMA relies on the fact that most tools check if they are allowed to create something before they actually create it, which the fading door tool does not do. So there is unfortunately nothing I can do to make it work with fading doors.
