### ISSUE TITLE
Constraint limits

### ISSUE THREAD

**Issue by Zytrol** [Weol/WUMA#64]
Is it possible to make limits for ropes, and other constraints? I have tried "ropeconstraints", "rope", and "constraints", yet no luck. Is there any way to do this as I see people constantly spamming ropes across the map and I have no idea how to limit this. Thank you in advance, and once again thank you for this amazing mod.

**Comment by Weol** [comment]
I'm afraid not. Its more or less the same reason as with the fading door.
