### ISSUE TITLE
How to check when a model is blocked before spawning it?

### ISSUE THREAD

**Issue by dvdvideo1234** [Weol/WUMA#70]
Hello,

Just what it says... I need to check if a certain model is `WUMA` enabled before I spawn it, so I ask is there a function like `WUMA.IsBlocked(model)` that I can call before I actually try to create the entity with the given model. Is there a proper way to access blacklist and whitelist ?

**Comment by Weol** [comment]
So you want to check if a model is restricted? Only model? Or other things as well such as entities and vehicles? Things can be restricted for one player but not another, so you will have to check if it is restricted for a specific player.

**Comment by dvdvideo1234** [comment]
Hi,

Is it possible to have two restrictive conditions? What I mean is `WUMA.IsBlocked(player, model)` restricting the model for specific player and `WUMA.IsBlocked(model)`, restricting the model for all the players ?

When done I will be able to check if it is restricted before creating the entity in [TA](https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/lua/trackassembly/trackasmlib.lua#L4545).

**Comment by Weol** [comment]
There is no such thing as restricting a model from all players. You MUST check if it is restricted for a specific player. Only `WUMA.IsBlocked(player, model) ` is possible to do.

**Comment by storm37000** [comment]
It would be best to use a vanilla hook like https://wiki.facepunch.com/gmod/SANDBOX:PlayerSpawnObject

**Comment by storm37000** [comment]
There is also a CPPI hook, although I dont think many prop protection addons implement it.
`CPPIAssignOwnership`
https://ulyssesmod.net/archive/CPPI_v1-3.pdf

**Comment by Weol** [comment]
True, using [PlayerSpawnProp](https://wiki.facepunch.com/gmod/SANDBOX:PlayerSpawnProp) is the way to go here. This will not only check if it is restricted in WUMA but also if it will hit a WUMA limit. It will also check whether any other addon will prevent it from being spawned.

**Comment by dvdvideo1234** [comment]
Hi, I am also fine with `WUMA.IsBlocked(player, model)` only as long as I can implement some restriction from my side it will be peachy prefect ;).

**Comment by dvdvideo1234** [comment]
Is there any way to blacklist models for [`function WUMA.PlayerSpawnProp(ply, mdl)`](https://github.com/Weol/wuma/blob/master/lua/wuma/hooks.lua#L23)? I see it only checks the props spawn limits and does not apply whitelist/blacklist control sets for the spawned models. I may be wrong though... Is it implemented somewhere else ? I used this in [`FPP`](https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L10) for example to override and test their hooks with my custom function,  but this is very hacky solution that I would not put in my code ( and I hope nobody ever will :D ):
```lua
  local tab = hook.GetTable()["PlayerSpawnProp"]
  asmlib.LogTable(tab, "PlayerSpawnProp")
  if(tab["FPP_SpawnProp"] and not tab["hack_FPP_SpawnProp"]) then
    local FPP_SpawnProp = tab["FPP_SpawnProp"]
    tab["FPP_SpawnProp"] = function(ply, mdl)
      print("------FPP------")
      print(ply, mdl)
      FPP_SpawnProp(ply, mdl)
    end
    tab["hack_FPP_SpawnProp"] = function(ply, mdl)
      return true
    end
  end
  if(true) then return true end

------FPP------
Player [1][[Sk$Bh]Trick or treat KID!]	models/props_c17/FurnitureWashingmachine001a.mdl
```

Conclusion: `FPP` and `WUMA` hook is called when `ENT:Spawn()` gets invoked. If a blacklist gets implemented and indexed in `hooks/function WUMA.PlayerSpawnProp(ply, mdl)`, this will solve @storm37000's problem I think.

**Comment by Weol** [comment]
When you say "apply whitelist/blacklist control" I assume you mean check if the model is restricted or not. [Line 29](https://github.com/Weol/wuma/blob/3eaa6102c490358bcc5c76f679b63d5dc741a137/lua/wuma/hooks.lua#L29) does this check.

**Comment by dvdvideo1234** [comment]
> There is no such thing as restricting a model from all players. You MUST check if it is restricted for a specific player. Only `WUMA.IsBlocked(player, model) ` is possible to do.

Ah, saw it... Though it was a library function instead of a custom one ( defined in player extension line 130 and calling `GetRestriction` function factory of `player.Restrictions` ).  So I assume @storm37000 must configure the blocked model for every player ?

**Comment by Weol** [comment]
Players inherit their usergroup's restrictions so there is only need to configure the blocked models per usergroup.

**Comment by dvdvideo1234** [comment]
So maybe it is due to the WUMA PP configuration because TA spawning big tracks is not blocked, @storm37000  ?

**Comment by Weol** [comment]
WUMA is not a prop protection addon, its a restrictions addon. It wont block spawning of any props unless the prop is restricted for the player who tries to spawn it.
