### ISSUE TITLE
Issues loading user groups with ULX

### ISSUE THREAD

**Issue by Megamezzomixer** [Weol/WUMA#73]
Hello there,

I currently have an odd problem. Whenever I am trying to open the wuma menu over ulx, I don't get the user groups displayed. It stays blank.

The console prints out this: 
`[wuma-master] addons/wuma-master/lua/wuma/extentions/playerextention.lua:316: bad argument #2 to 'format' (no value)

  1. format - [C]:-1

   2. fn - addons/wuma-master/lua/wuma/extentions/playerextention.lua:316

    3. Call - addons/ulib-master/lua/ulib/shared/hook.lua:109

     4. PlayerSpawn - gamemodes/base/gamemode/player.lua:263`

The newest version is in use.

**Comment by Megamezzomixer** [comment]
![grafik](https://user-images.githubusercontent.com/21281507/166150437-01421710-1f1f-42cb-acc1-c347644a4cc4.png)
Menu currently looks like this.

Some of my usergroups have spaces in them, but that wasn't an issue before.

**Comment by Megamezzomixer** [comment]
It actually started working again.
My guess was a bad file upload or something. After wiping the addon and uploading it to the server again, it worked flawlessly.

**Comment by Weol** [comment]
No, I pushed an update yesterday that should fix a number of bugs. Good to know it works👌
