### ISSUE TITLE
Support For Secondary Usergroups

### ISSUE THREAD

**Issue by briang112** [Weol/WUMA#9]
Hi, could you add support for WUMA to detect secondary usergroups? I don't think it would be hard and would be great for servers with donation systems:

https://www.gmodstore.com/scripts/view/4270/any-admin-mod-secondary-user-groups-easy-donation-system

Thanks.

**Comment by Weol** [comment]
Changing WUMA to detect decondary usergroups is not trivial. I rely on CAMI to sort out usergroups for me, and changing that is not very wise. 

There may be other options but those will be hard to find, since I don't have access to the code for secondary usergroups.

**Comment by briang112** [comment]
I could contact him for you and ask for a copy to develop with if you'd like.

**Comment by Weol** [comment]
Honestly, I don't think its worth the time. I'm sorry.
